### ISSUE TITLE
Not running in Tablet

### ISSUE THREAD

**Issue by YashNagayach** [InQBarna/TableFixHeaders#128] opened 2018-07-10 12:21 UTC
Process: com.app.goveva, PID: 1792
    java.lang.NullPointerException: Attempt to get length of null array
        at com.inqbarna.tablefixheaders.TableFixHeaders.sumArray(TableFixHeaders.java:616)
        at com.inqbarna.tablefixheaders.TableFixHeaders.computeHorizontalScrollOffset(TableFixHeaders.java:356)

Getting this when running on the tablet or any other android bigger size device (> 5").
But running properly on smaller devices(<= 5")

**Comment by BraisGabin** [comment] 2018-07-16 08:59
There's nothing at line 616. Anyway this crash is not related with the device size. It must be your code doing different things depend on device display size. Why is the array `null`?

**Comment by iman2420** [comment] 2019-04-25 14:39
Do you implement TableFixHeaders view in separate threat??

**Comment by sandeepyohans** [comment] 2019-09-19 09:05
I'm getting this exception after adding following line in xml layout code:
`                android:scrollbars="horizontal|vertical"
`
After removing this line it works fine. 
Not: I'm running it on Mobile phone with Android 8.1

**Comment by mkkabi** [comment] 2020-08-17 01:18
was anyone able to find a solution to this issue? I'm trying to get this resolved in one of my applications. Already tried everything I could think of. A funny thing is that it works fine in another app. I've tried to replicate everything I could related to the implementation of the tablefixedheaders or even to how that other app uses it. And the issue is still there.

**Closed** 2020-11-26 16:40 UTC
